name: CI-Workflow

on:
  push:
    branches:
      - main
      - Lab3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Dependencies
        run: |
          cd app_python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linter
        run: |
          cd app_python
          pip install flake8
          flake8 .

      - name: Tests
        run: |
          cd app_python
          python app.py &
          sleep 5
          python test.py

      - name: Snyk
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          cd app_python
          snyk test --code 

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd app_python
          docker build -t anastasiamartynova/my-docker-repo:latest .
          docker tag anastasiamartynova/my-docker-repo:latest anastasiamartynova/my-docker-repo:latest
          docker push anastasiamartynova/my-docker-repo:latest