name: CI-Workflow

on:
  push:
    branches:
      - main
      - Lab3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Dependencies
        run: |
          cd app_python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linter
        run: |
          cd app_python
          pip install flake8
          flake8 .

      - name: Tests
        run: |
          cd app_python
          python app.py &
          sleep 5
          python test.py

snyk_check:
  name: Run Snyk
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python-3.10@master
      with:
        args: --skip-unresolved app_python/
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}